/**
 * BrandSystem Component
 * =====================
 * Technical Brand Kit and Design System showcase
 */

import { Shield, Leaf, Database } from 'lucide-react';

export const BrandSystem = () => {
  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-bold text-slate-900 font-serif mb-2">Technical Brand Kit</h2>
        <p className="text-slate-600 max-w-3xl">
          This design system is built to ensure trust, authority, and organic growth. It avoids "startup" aesthetics in
          favor of "institutional permanence."
        </p>
      </div>

      {/* Color Palette */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="space-y-2">
          <div className="h-24 rounded-lg bg-slate-900 shadow-lg"></div>
          <h4 className="font-bold text-slate-900">Sovereignty Blue</h4>
          <p className="text-xs text-slate-500">Slate-900 (#0f172a)</p>
          <p className="text-xs text-slate-600">Used for navigation, primary text, and structural elements. Represents the law and stability.</p>
        </div>
        <div className="space-y-2">
          <div className="h-24 rounded-lg bg-emerald-700 shadow-lg"></div>
          <h4 className="font-bold text-slate-900">Land Trust Green</h4>
          <p className="text-xs text-slate-500">Emerald-700 (#047857)</p>
          <p className="text-xs text-slate-600">Used for primary actions, growth metrics, and success states. Represents the land and healing.</p>
        </div>
        <div className="space-y-2">
          <div className="h-24 rounded-lg bg-amber-500 shadow-lg"></div>
          <h4 className="font-bold text-slate-900">Asset Gold</h4>
          <p className="text-xs text-slate-500">Amber-500 (#f59e0b)</p>
          <p className="text-xs text-slate-600">Used for monetary value, alerts, and highlights. Represents the wealth generated by families.</p>
        </div>
        <div className="space-y-2">
          <div className="h-24 rounded-lg bg-slate-50 border border-slate-200"></div>
          <h4 className="font-bold text-slate-900">Protocol Canvas</h4>
          <p className="text-xs text-slate-500">Slate-50 (#f8fafc)</p>
          <p className="text-xs text-slate-600">Backgrounds. Clean, distraction-free, paper-like.</p>
        </div>
      </div>

      <hr className="border-slate-200" />

      {/* Typography & Iconography */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h3 className="font-bold text-lg mb-4">Typography Logic</h3>
          <div className="space-y-4">
            <div className="p-4 border border-slate-200 rounded-lg">
              <p className="text-3xl font-serif text-slate-900 mb-2">The Dignity Protocol</p>
              <p className="text-xs text-slate-500 uppercase tracking-widest mb-1">Serif Headings</p>
              <p className="text-sm text-slate-600">Used for titles and major statements to evoke legal/historical weight.</p>
            </div>
            <div className="p-4 border border-slate-200 rounded-lg">
              <p className="text-base font-sans text-slate-900 mb-2">Families achieving economic stability through verifiable metrics.</p>
              <p className="text-xs text-slate-500 uppercase tracking-widest mb-1">Sans-Serif Body</p>
              <p className="text-sm text-slate-600">Used for UI elements, data tables, and reading text for maximum clarity.</p>
            </div>
          </div>
        </div>

        <div>
          <h3 className="font-bold text-lg mb-4">Iconography</h3>
          <div className="flex gap-4 mb-4">
            <div className="p-3 bg-slate-100 rounded-lg">
              <Shield className="w-6 h-6 text-slate-900" />
            </div>
            <div className="p-3 bg-emerald-100 rounded-lg">
              <Leaf className="w-6 h-6 text-emerald-700" />
            </div>
            <div className="p-3 bg-amber-100 rounded-lg">
              <Database className="w-6 h-6 text-amber-600" />
            </div>
          </div>
          <p className="text-sm text-slate-600">
            Icons should be outlined (Lucide React), clean, and functional. Avoid "cartoonish" or "filled" styles unless
            indicating a button state.
          </p>
        </div>
      </div>
    </div>
  );
};

export default BrandSystem;
